import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Shield, Globe, Lock, AlertTriangle, Loader2 } from "lucide-react";
import { useVpsTool } from "@/hooks/useVpsTool";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Link } from "react-router-dom";

export default function SecurityAuditor() {
  const { runTool, loading } = useVpsTool();
  const [domain, setDomain] = useState("");
  const [report, setReport] = useState<any>(null);

  // Load past scans
  const { data: pastScans = [] } = useQuery({
    queryKey: ["security-scans"],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return [];
      const { data } = await supabase
        .from("security_scans")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        .limit(20);
      return data || [];
    },
  });

  const handleAudit = async () => {
    if (!domain.trim()) return;
    const [nmap, nikto] = await Promise.all([
      runTool("nmap", domain.trim(), { flags: "-sV --top-ports 50" }),
      runTool("nikto", domain.trim()),
    ]);
    setReport({ domain: domain.trim(), nmap, nikto, date: new Date().toISOString() });
  };

  const handleDownload = () => {
    if (!report) return;
    const content = `
=== VEXTAGON SECURITY AUDIT REPORT ===
Domain: ${report.domain}
Date: ${new Date(report.date).toLocaleString("pt-BR")}
Generated by: Vextagon Platform (Alluzion Corporate)

--- NMAP RESULTS ---
${typeof report.nmap?.output === "string" ? report.nmap.output : JSON.stringify(report.nmap?.output || report.nmap, null, 2)}

--- NIKTO RESULTS ---
${typeof report.nikto?.output === "string" ? report.nikto.output : JSON.stringify(report.nikto?.output || report.nikto, null, 2)}

=== END OF REPORT ===
Powered by Vextagon | Alluzion Corporate
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `vextagon-audit-${report.domain}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-lg font-semibold tracking-wide text-foreground">Security Auditor</h1>
          <p className="text-xs text-muted-foreground mt-0.5">Auditoria real via Nmap + Nikto na VPS Kali</p>
        </div>
        {report && (
          <Button onClick={handleDownload} size="sm" className="text-xs font-medium">
            <Download className="mr-1.5 h-3.5 w-3.5" /> Baixar Relatório
          </Button>
        )}
      </div>

      {/* Input */}
      <div className="v-card p-4">
        <div className="flex gap-2">
          <Input
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
            placeholder="dominio.com"
            className="bg-secondary/50 font-mono text-xs border-border flex-1"
            onKeyDown={(e) => e.key === "Enter" && handleAudit()}
          />
          <Button onClick={handleAudit} disabled={loading} size="sm" className="text-xs">
            {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" /> : <Shield className="h-3.5 w-3.5 mr-1" />}
            {loading ? "Auditando..." : "Auditar"}
          </Button>
        </div>
      </div>

      {loading && (
        <div className="v-card flex flex-col items-center py-12">
          <Loader2 className="h-10 w-10 text-primary animate-spin" />
          <p className="mt-3 font-mono text-xs text-muted-foreground">Executando auditoria em {domain}...</p>
        </div>
      )}

      {/* Report */}
      {report && !loading && (
        <div className="space-y-4">
          <div className="v-card p-4">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="h-3.5 w-3.5 text-primary" />
              <p className="v-section-title">Relatório — {report.domain}</p>
            </div>
            <div className="space-y-3">
              <div>
                <p className="v-label mb-1.5">Nmap Output</p>
                <pre className="rounded bg-secondary/40 p-3 font-mono text-[10px] text-foreground/80 overflow-auto max-h-[300px] whitespace-pre-wrap">
                  {typeof report.nmap?.output === "string" ? report.nmap.output : JSON.stringify(report.nmap?.output || report.nmap, null, 2)}
                </pre>
              </div>
              <div>
                <p className="v-label mb-1.5">Nikto Output</p>
                <pre className="rounded bg-secondary/40 p-3 font-mono text-[10px] text-foreground/80 overflow-auto max-h-[300px] whitespace-pre-wrap">
                  {typeof report.nikto?.output === "string" ? report.nikto.output : JSON.stringify(report.nikto?.output || report.nikto, null, 2)}
                </pre>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Past Scans */}
      {pastScans.length > 0 && !report && (
        <div className="v-card overflow-hidden">
          <div className="border-b border-border px-4 py-3">
            <p className="v-section-title">Scans Anteriores</p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-border">
                  <th className="px-4 py-2.5 text-left v-label">Domínio</th>
                  <th className="px-4 py-2.5 text-left v-label">Tipo</th>
                  <th className="px-4 py-2.5 text-left v-label">Score</th>
                  <th className="px-4 py-2.5 text-left v-label">Data</th>
                </tr>
              </thead>
              <tbody>
                {pastScans.map((scan: any) => (
                  <tr key={scan.id} className="border-b border-border/40 hover:bg-secondary/30 transition-colors">
                    <td className="px-4 py-2.5 font-mono text-foreground">{scan.domain}</td>
                    <td className="px-4 py-2.5"><Badge variant="outline" className="text-[10px]">{scan.scan_type}</Badge></td>
                    <td className="px-4 py-2.5 font-mono text-cyan">{scan.score || "—"}</td>
                    <td className="px-4 py-2.5 font-mono text-muted-foreground">{new Date(scan.created_at).toLocaleDateString("pt-BR")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Empty */}
      {!loading && !report && pastScans.length === 0 && (
        <div className="v-card flex flex-col items-center justify-center py-16 text-center">
          <FileText className="h-10 w-10 text-muted-foreground mb-3" />
          <p className="text-sm text-muted-foreground">Nenhuma auditoria executada</p>
          <p className="text-xs text-muted-foreground mt-1">Execute scans reais com Nmap e Nikto via VPS Kali Linux</p>
          <Link to="/admin" className="mt-3 text-xs text-cyan hover:underline">Configurar VPS no Admin →</Link>
        </div>
      )}
    </div>
  );
}
